web/protected/controllers/BugController.php
<?php

class BugController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$bugRevision = BugRevision::model()->findAllByAttributes(array('bugid'=>$id));
		$dataProvider=new CArrayDataProvider(
			$bugRevision, 
			array(
				'id'=>'bugRevsions', //this is an identifier for the array data provider
				'sort'=>false,
				'keyField'=>'bugid', //this is what will be considered your key field
				'pagination'=>array(
					'pageSize'=>10, //eureka! you can configure your pagination from here
				),
			)
		);
		$screenshots = ScreenShot::model()->findAllByAttributes(array('bugid'=>$id));
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'dataProvider'=>$dataProvider,
			'screenshots'=>$screenshots,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Bug;
		$projects = Project::model()->findAll();
		$listData = CHtml::listData($projects, 'projectid', 'projectTitle');
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bug']))
		{
			$model->attributes=$_POST['Bug'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->bugid));
		}

		$this->render('create',array(
			'model'=>$model,
			'listData'=>$listData,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$projects = Project::model()->findAll();
		$listData = CHtml::listData($projects, 'projectid', 'projectTitle');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bug']))
		{
			$model->attributes=$_POST['Bug'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->bugid));
		}

		$this->render('update',array(
			'model'=>$model,
			'listData'=>$listData,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Bug');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Bug('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Bug']))
			$model->attributes=$_GET['Bug'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Bug the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Bug::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Bug $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='bug-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

web/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
		);
	}

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	public function actionDashboard()
	{
		//Generate User and team Info
		$user = User::model()->findByPk(array('userid' => yii::app()->user->getid()));
		$members = TeamMembers::model()->findAllByAttributes(array('userid'=>$user->userid));
		$teams = array();
		foreach ($members as $m){
			array_push($teams, Team::model()->findByPk($m->teamid));
		}

		//Generate Projects Information
		//Active Projects
		$projects = array();
		if(!empty($teams)){
			foreach ($teams as $t){
				$projects = Project::model()->findAllByAttributes(array('projectTeam'=>$t->teamid, 'active'=>true));
			}
		}
		$userProjects = Project::model()->findAllByAttributes(array('projectOwner'=>$user->userid, 'active'=>true));
		foreach ($userProjects as $up){
			$match = false;
			foreach($projects as $p){
				if ($up->projectid == $p->projectid){
					$match = true;
				}
			}
			if (!$match){
				array_push($projects, $up);
			}
		}
		//Copmpleted Projects
		$completeProjects = Project::model()->findAllByAttributes(array('projectTeam'=>$t->teamid, 'active'=>false));
		$completeUP = Project::model()->findAllByAttributes(array('projectOwner'=>$user->userid, 'active'=>false));
		foreach ($completeUP as $cup){
			$match = false;
			foreach($completeProjects as $cp){
				if ($cup->projectid == $cp->projectid){
					$match = true;
				}
			}
			if (!$match){
				array_push($completeProjects, $cup);
			}
		}

		//Generate Bug Info
		$bugs = array();
		if(!empty($projects)){
			foreach($projects as $p){
				$bugs = Bug::model()->findAllByAttributes(array('projectid'=>$p->projectid, 'active'=>true));
			}
		}

		//Generate Invite Info
		$invites = array();
		$invitations = Invitations::model()->findAllByAttributes(array('invitee'=>yii::app()->user->getId(), 'completed'=>false));
		foreach ($invitations as $inv){
			if($inv->completed === 0){
				array_push($invites, $inv);
			}
		}
		$userInvites = Invitations::model()->findAllByAttributes(array('inviteeEmail'=>$user->email, 'completed'=>false));
		if(isset($userInvites)){
			foreach($userInvites as $ui){
				$match = false;
				foreach($invites as $i){
					if($i->invitationid === $ui->invitationid){
						$match = true;
					}
				}
				if(!$match){
					array_push($invites, $ui);
				}
			}
		}


		//Generate Tabs
		$tabs = array();
		array_push($tabs,array('label'=>'Dashboard','content'=>$this->renderPartial('_overview', array(), true),'active'=>true)); //Dashboard Overview Tab
		array_push($tabs,array('label'=>'Profile','content'=>$this->renderPartial('_profile', array('user'=>$user, 'teams'=>$teams), true),'active' => false,)); //User Profile Tab
		array_push($tabs,array('label'=>'Projects','content'=>$this->renderPartial('_projects', array('projects'=>$projects, 'completeProjects'=>$completeProjects), true),'active'=> false,)); //Projects Tab
		array_push($tabs,array('label'=>'Bugs','content'=>$this->renderPartial('_bugs', array('bugs'=>$bugs), true),'active'=> false,)); //Bugs Tab
		array_push($tabs,array('label'=>'Teams','content'=>$this->renderPartial('_teams', array('teams'=>$teams), true),'active'=> false,)); //Teams Tab
		array_push($tabs,array('label'=>'Invites','content'=>$this->renderPartial('_invites', array('invites'=>$invites), true), 'active'=>false,));

		$this->render('dashboard', array('tabs'=>$tabs));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()){
				if(Yii::app()->user->returnUrl != Yii::app()->BaseUrl.'/index.php'){
					$this->redirect(Yii::app()->user->returnUrl);
				} else {
					$this->redirect('dashboard');
				}
			}	
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

web/protected/controllers/TeamController.php
<?php

class TeamController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(),
				'roles'=>array('guest'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','view', 'create','update'),
				'roles'=>array('authenticated'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$users = TeamMembers::model()->findAllByAttributes(array('teamid'=>$id));
		$members = array();
		foreach($users as $u){
			array_push($members, User::model()->findByPk($u->userid));
		}
		$this->render('view',array('model'=>$this->loadModel($id), 'members'=>$members));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Team;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Team']))
		{
			$model->attributes=$_POST['Team'];
			if($model->save()){
				$member = new TeamMembers;
				$member->userid = yii::app()->user->getId();
				$member->teamid = $model->teamid;
				$member->save();
				$this->redirect(array('team/view/'.$model->teamid));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Team']))
		{
			$model->attributes=$_POST['Team'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->teamid));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Team');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Team('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Team']))
			$model->attributes=$_GET['Team'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Team the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Team::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Team $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='team-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

web/protected/views/site/_bugs.php
<?php
	echo "<h3>Bugs</h3>";

	$dataProvider=new CArrayDataProvider(
		$bugs, 
		array(
		'id'=>'bugs', //this is an identifier for the array data provider
		'sort'=>false,
		'keyField'=>'bugid', //this is what will be considered your key field
		'pagination'=>array(
			'pageSize'=>10, //eureka! you can configure your pagination from here
			),
		)
	);

	$this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$dataProvider,
		'emptyText'=>'There are currently no bugs with the projects you are working on',
		'columns'=>array(
			array(            // display 'create_time' using an expression
				'name'=>'Bug Title',
				'value'=>'$data->bugTitle',
			),
			array(
				'name'=>'Project',
				'type'=>'html',
				'value'=>'CHtml::link(Project::model()->findByPk($data->projectid)->projectTitle, array("project/view", "id"=>$data->projectid))',
			),
			array(
				'name'=>'Team',
				'type'=>'html',
				'value'=>'CHtml::link(Team::model()->findByPk(Project::model()->findByPk($data->projectid)->projectTeam)->teamName, array("team/view", "id"=>Project::model()->findByPk($data->projectid)->projectTeam))',
			),
			array(
				'name'=>'View',
				'type'=>'html',
				'value'=>'CHtml::link("View", array("bug/view", "id"=>$data->bugid))',
				),
		),
	));
?>

web/protected/views/site/_invites.php
<?php
	echo "<h3>My Invitations</h3>";  

	$dataProvider=new CArrayDataProvider(
		$invites, 
		array(
		'id'=>'invites', //this is an identifier for the array data provider
		'sort'=>false,
		'keyField'=>'invitationid', //this is what will be considered your key field
		'pagination'=>array(
			'pageSize'=>10, //eureka! you can configure your pagination from here
			),
		)
	);

	$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>$dataProvider,
    'emptyText'=>'You have no incomplete invitations',
    'columns'=>array(
        array(            // display 'create_time' using an expression
            'name'=>'Team Name',
            'value'=>'Team::model()->findByPk($data->team)->teamName',
        ),
        array(            // display 'create_time' using an expression
            'name'=>'Invitation Code',
            'value'=>'$data->rString',
        ),
        array(
        	'name'=>'Accept',
        	'value'=>'CHtml::Link("accept", array("invitations/accept", "rString"=>$data->rString))',
        	'type'=>'html',
        ),
        array(
        	'name'=>'Decline',
        	'value'=>'CHtml::Link("decline", array("invitations/decline", array("rString"=>$data->rString)))',
        	'type'=>'html',
        ),
    ),
));
?>

web/protected/views/site/_overview.php
<div class="span-23 showgrid">
    <div class="dashboardIcons span-16">
        <div class="dashIcon span-3">
            <?php echo CHtml::link(CHtml::Image(Yii::app()->theme->baseUrl.'/images/big_icons/project.png', 'New Project'), array('project/create')); ?>
            <div class="dashIconText"><?php echo CHtml::link('New Project', array('project/create')); ?></div>
        </div>
        
        <div class="dashIcon span-3">
            <?php echo CHtml::link(CHtml::Image(Yii::app()->theme->baseUrl.'/images/big_icons/bug.png', 'New Bug'), array('bug/create')); ?>
            <div class="dashIconText"><?php echo CHtml::link('New Bug', array('bug/create')); ?></div>
        </div>
        
        <div class="dashIcon span-3">
            <?php echo CHtml::link(CHtml::Image(Yii::app()->theme->baseUrl.'/images/big_icons/team.png', 'New Team'), array('team/create')); ?>
            <div class="dashIconText"><?php echo CHtml::link('New Team', array('team/create')); ?></div>
        </div>
    </div>
</div>

web/protected/views/site/_profile.php
<?php
	$teamNames = array();
	foreach ($teams as $t){
		array_push($teamNames, CHtml::link($t->teamName, array('team/view/', 'id'=>$t->teamid)));
	}

	$this->widget(
		'booster.widgets.TbDetailView',
		array(
			'data' => $user,
			'attributes' => array(
				array('name' => 'userName', 'label' => 'Username'),
				array('name' => 'firstName', 'label' => 'First name'),
				array('name' => 'lastName', 'label' => 'Last name'),
				array('value' => implode('<br/>', $teamNames), 'label' => 'Teams', 'type'=>'html'),
			),
		)
	);
?>

web/protected/views/site/_projects.php
<?php
	echo "<h3>Projects that i am involved with</h3>";

	$dataProvider=new CArrayDataProvider(
		$projects, 
		array(
		'id'=>'projects', //this is an identifier for the array data provider
		'sort'=>false,
		'keyField'=>'projectid', //this is what will be considered your key field
		'pagination'=>array(
			'pageSize'=>10, //eureka! you can configure your pagination from here
			),
		)
	);

	$this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$dataProvider,
		'emptyText'=>'You have no active projects',
		'summaryText' => '',
		'columns'=>array(
			array(            // display 'create_time' using an expression
				'name'=>'Project Tile',
				'value'=>'$data->projectTitle',
			),
			array(
				'name'=>'Team Involved',
				'value'=>'Team::model()->findByPk($data->projectTeam)->teamName',
			),
			array(
				'name'=>'# of Bugs',
				'value'=>'Bug::model()->countByAttributes(array("projectid"=>$data->projectid))'
			),
			array(
				'name'=>'View',
				'type'=>'html',
				'value'=>'CHtml::link("View", array("project/view", "id"=>$data->projectid))',
			),
		),
	));

	echo "<h3>Completed Projects</h3>";
	$cDataProvider=new CArrayDataProvider(
		$completeProjects, 
		array(
			'id'=>'projects', //this is an identifier for the array data provider
			'sort'=>false,
			'keyField'=>'projectid', //this is what will be considered your key field
			'pagination'=>array(
				'pageSize'=>10, //eureka! you can configure your pagination from here
			),
		)
	);

	$this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$cDataProvider,
		'emptyText'=>'You have not been involved with any completed projects',
		'summaryText' => '',
		'columns'=>array(
			array(            // display 'create_time' using an expression
				'name'=>'Project Tile',
				'value'=>'$data->projectTitle',
			),
			array(
				'name'=>'Team Involved',
				'value'=>'Team::model()->findByPk($data->projectTeam)->teamName',
			),
			array(
				'name'=>'# of Bugs',
				'value'=>'Bug::model()->countByAttributes(array("projectid"=>$data->projectid))'
			),
			array(
				'name'=>'View',
				'type'=>'html',
				'value'=>'CHtml::link("View", array("project/view", "id"=>$data->projectid))',
			),
		),
	));
?>

web/protected/views/site/_teams.php
<?php
	echo "<h3>My Teams</h3>";

	$dataProvider=new CArrayDataProvider(
		$teams, 
		array(
		'id'=>'teams', //this is an identifier for the array data provider
		'sort'=>false,
		'keyField'=>'teamid', //this is what will be considered your key field
		'pagination'=>array(
			'pageSize'=>10, //eureka! you can configure your pagination from here
			),
		)
	);

	$this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$dataProvider,
		'emptyText'=>'You have not currently involved with any teams',
		'columns'=>array(
			array(            // display 'create_time' using an expression
				'name'=>'Team Name',
				'value'=>'$data->teamName',
			),
			array(
				'name'=>'# of Members',
				'value'=>'TeamMembers::model()->countByAttributes(array("teamid"=>$data->teamid))',
			),
			array(
				'name'=>'View',
				'type'=>'html',
				'value'=>'CHtml::link("View", array("team/view", "id"=>$data->teamid))',
				),
		),
	));

?>

web/protected/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

web/protected/views/site/dashboard.php
<?php
	/* @var $this UserController */
	/* @var $model User */
	$this->breadcrumbs=array('Dashboard');
?>

<div class="col-xs-12 col-md-6">
	<?php $this->widget(
		'booster.widgets.TbTabs',
		array(
			'type' => 'tabs',
			'placement' => 'left',
			'tabs' => $tabs,
		)
	);?>
</div>

web/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

web/protected/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

<p>Congratulations! You have successfully created your Yii application.</p>

<p>You may change the content of this page by modifying the following two files:</p>
<ul>
	<li>View file: <code><?php echo __FILE__; ?></code></li>
	<li>Layout file: <code><?php echo $this->getLayoutFile('main'); ?></code></li>
</ul>

<p>For more details on how to further develop this application, please read
the <a href="http://www.yiiframework.com/doc/">documentation</a>.
Feel free to ask in the <a href="http://www.yiiframework.com/forum/">forum</a>,
should you have any questions.</p>

<?
echo Yii::app()->BaseUrl.'/index.php';
echo "<br/>";
echo Yii::app()->user->returnUrl;
?>