web/protected/models/Bug.php
<?php

/**
 * This is the model class for table "Bug".
 *
 * The followings are the available columns in table 'Bug':
 * @property integer $bugid
 * @property string $bugTitle
 * @property string $bugDescription
 * @property integer $projectid
 * @property integer $active
 *
 * The followings are the available model relations:
 * @property Project $project
 * @property BugRevision[] $bugRevisions
 * @property ScreenShot[] $screenShots
 */
class Bug extends BackupRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'Bug';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('bugTitle, bugDescription, projectid', 'required'),
			array('projectid, active', 'numerical', 'integerOnly'=>true),
			array('bugTitle', 'length', 'max'=>45),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('bugid, bugTitle, bugDescription, projectid, active', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'project' => array(self::BELONGS_TO, 'Project', 'projectid'),
			'bugRevisions' => array(self::HAS_MANY, 'BugRevision', 'bugid'),
			'screenShots' => array(self::HAS_MANY, 'ScreenShot', 'bugid'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'bugid' => 'Bugid',
			'bugTitle' => 'Bug Name',
			'bugDescription' => 'Description of Bug',
			'projectid' => 'Projectid',
			'active' => 'Active',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('bugid',$this->bugid);
		$criteria->compare('bugTitle',$this->bugTitle,true);
		$criteria->compare('bugDescription',$this->bugDescription,true);
		$criteria->compare('projectid',$this->projectid);
		$criteria->compare('active',$this->active);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Bug the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

web/protected/controllers/BugController.php
<?php

class BugController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$bugRevision = BugRevision::model()->findAllByAttributes(array('bugid'=>$id));
		$dataProvider=new CArrayDataProvider(
			$bugRevision, 
			array(
				'id'=>'bugRevsions', //this is an identifier for the array data provider
				'sort'=>false,
				'keyField'=>'bugid', //this is what will be considered your key field
				'pagination'=>array(
					'pageSize'=>10, //eureka! you can configure your pagination from here
				),
			)
		);
		$screenshots = ScreenShot::model()->findAllByAttributes(array('bugid'=>$id));
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'dataProvider'=>$dataProvider,
			'screenshots'=>$screenshots,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Bug;
		$projects = Project::model()->findAll();
		$listData = CHtml::listData($projects, 'projectid', 'projectTitle');
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bug']))
		{
			$model->attributes=$_POST['Bug'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->bugid));
		}

		$this->render('create',array(
			'model'=>$model,
			'listData'=>$listData,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$projects = Project::model()->findAll();
		$listData = CHtml::listData($projects, 'projectid', 'projectTitle');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bug']))
		{
			$model->attributes=$_POST['Bug'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->bugid));
		}

		$this->render('update',array(
			'model'=>$model,
			'listData'=>$listData,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Bug');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Bug('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Bug']))
			$model->attributes=$_GET['Bug'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Bug the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Bug::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Bug $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='bug-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

web/protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('create', ),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index', 'update', 'view'),
				'roles'=>array('authenticated'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$membership = TeamMembers::model()->findAllByAttributes(array('userid'=>$id));
		$teams = array();
		foreach ($membership as $m){
			array_push($teams, Team::model()->findByPk($m->teamid));
		}
		$this->render('view',array('model'=>$this->loadModel($id), 'teams'=>$teams));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->password = CPasswordHelper::hashPassword($model->password1);
			$auth = Yii::app()->authManager;
			if($model->save())
				$auth->assign('authenticated', $model->userid, null, null);
				$auth->save();
				$this->redirect(array('view','id'=>$model->userid));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->userid));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

web/protected/views/bug/_form.php
<?php
/* @var $this BugController */
/* @var $model Bug */
/* @var $form TbActiveForm */

$form = $this->beginWidget(
	'booster.widgets.TbActiveForm',
	array(
		'id' => 'bug-form',
		'htmlOptions' => array('class' => 'well'), // for inset effect
	)
);
 
echo $form->textFieldGroup($model, 'bugTitle');
if(!isset($_GET['projectid'])){
	echo $form->dropDownListGroup($model, 'projectid', array('widgetOptions'=>array('data'=>$listData)));
}else{
	echo $form->hiddenField($model, 'projectid', array('value'=>$_GET['projectid']));
}
echo $form->textAreaGroup($model,'bugDescription');
echo $form->switchGroup($model, 'active');

$this->widget(
'booster.widgets.TbButton',
array('buttonType' => 'submit', 'label' => 'submit bug')
);
 
$this->endWidget();
unset($form);
?>

web/protected/views/bug/_search.php
<?php
/* @var $this BugController */
/* @var $model Bug */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'bugid'); ?>
		<?php echo $form->textField($model,'bugid'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'bugTitle'); ?>
		<?php echo $form->textField($model,'bugTitle',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'bugDescription'); ?>
		<?php echo $form->textArea($model,'bugDescription',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'projectid'); ?>
		<?php echo $form->textField($model,'projectid'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'active'); ?>
		<?php echo $form->textField($model,'active'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'screenshotid'); ?>
		<?php echo $form->textField($model,'screenshotid'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

web/protected/views/bug/_view.php
<?php
/* @var $this BugController */
/* @var $data Bug */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('bugid')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->bugid), array('view', 'id'=>$data->bugid)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('bugTitle')); ?>:</b>
	<?php echo CHtml::encode($data->bugTitle); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('bugDescription')); ?>:</b>
	<?php echo CHtml::encode($data->bugDescription); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('projectid')); ?>:</b>
	<?php echo CHtml::encode($data->projectid); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('active')); ?>:</b>
	<?php echo CHtml::encode($data->active); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('screenshotid')); ?>:</b>
	<?php echo CHtml::encode($data->screenshotid); ?>
	<br />


</div>

web/protected/views/bug/admin.php
<?php
/* @var $this BugController */
/* @var $model Bug */

$this->breadcrumbs=array(
	'Bugs'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Bug', 'url'=>array('index')),
	array('label'=>'Create Bug', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#bug-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Bugs</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'bug-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'bugid',
		'bugTitle',
		'bugDescription',
		'projectid',
		'active',
		'screenshotid',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

web/protected/views/bug/create.php
<?php
/* @var $this BugController */
/* @var $model Bug */

$this->breadcrumbs=array(
	'Bugs'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Bug', 'url'=>array('index')),
	array('label'=>'Manage Bug', 'url'=>array('admin')),
);
?>

<h1>Create Bug</h1>

<?php $this->renderPartial('_form', array('model'=>$model, 'listData'=>$listData)); ?>

web/protected/views/bug/index.php
<?php
/* @var $this BugController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Bugs',
);

$this->menu=array(
	array('label'=>'Create Bug', 'url'=>array('create')),
	array('label'=>'Manage Bug', 'url'=>array('admin')),
);
?>

<h1>Bugs</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

web/protected/views/bug/update.php
<?php
/* @var $this BugController */
/* @var $model Bug */

$this->breadcrumbs=array(
	'Bugs'=>array('index'),
	$model->bugid=>array('view','id'=>$model->bugid),
	'Update',
);

$this->menu=array(
	array('label'=>'List Bug', 'url'=>array('index')),
	array('label'=>'Create Bug', 'url'=>array('create')),
	array('label'=>'View Bug', 'url'=>array('view', 'id'=>$model->bugid)),
	array('label'=>'Manage Bug', 'url'=>array('admin')),
);
?>

<h1>Update Bug <?php echo $model->bugid; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model, 'listData'=>$listData)); ?>

web/protected/views/bug/view.php
<?php
/* @var $this BugController */
/* @var $model Bug */

$project = Project::model()->findByPk($model->projectid);
$team = Team::model()->findByPk($project->projectTeam);

$this->breadcrumbs=array(
	$project->projectTitle =>array('project/view', 'id'=>$model->projectid),
	$model->bugTitle,
);

$this->menu=array(
	array('label'=>'List Bug', 'url'=>array('index')),
	array('label'=>'Create Bug', 'url'=>array('create')),
	array('label'=>'Update Bug', 'url'=>array('update', 'id'=>$model->bugid)),
	array('label'=>'Delete Bug', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->bugid),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Bug', 'url'=>array('admin')),
	array('label'=>'Upload A Screenshot', 'url'=>array('screenShot/create', 'bugid'=>$model->bugid)),
);

echo "<h1>View Bug: $model->bugTitle</h1>";

$this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'bugTitle',
		'bugDescription',
		array(
			'name'=>'Project',
			'type'=>'html',
			'value'=>CHtml::link($project->projectTitle, array('project/view', 'id'=>$model->projectid)),
		),
		array(
			'name'=>'Team',
			'type'=>'html',
			'value'=>CHtml::link($team->teamName, array('team/view', 'id'=>$team->teamid)),
		),
	),
)); 

echo "<h2>Bug Revisions</h2>";
$this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$dataProvider,
	'emptyText'=>'There has Been no chnages to this bug submission',
	'columns'=>array(
		array(            // display 'create_time' using an expression
			'name'=>'Revision Time',
			'value'=>'date("M j Y g:i A", strtotime($data->revisionTime));',
		),
		array(
			'name'=>'Bug Title',
			'value'=>'$data->bugTitle',
		),
		array(
			'name'=>'Bug Description',
			'value'=>'$data->bugDescription'
		),
		array(
			'name'=>'Active',
			'value'=>'$data->active==0? "false" : "true"',
		),
		array(
			'name'=>'Edited By',
			'type'=>'html',
			'value'=>'CHtml::link(User::model()->findByPk($data->revisedBy)->userName, array("user/view", "id"=>$data->revisedBy))',
		),
	),
));


echo "<h2>Screenshots</h2>";

foreach ($screenshots as $s){
	echo CHtml::image(
		$this->createAbsoluteUrl('screenShot/display', array('id'=>$s->screenshotid)), 
		'Screenshot of '.$model->bugTitle,
		array(
			'width'=>'100%',
			'max-height'=>'100%',
			'title'=>'image title here',
			'data-toggle' => 'modal',
			'data-target' => '#imageModal'.$s->screenshotid,
		) 
	);
	echo "<br/>Uploaded by ".User::model()->findByPk($s->uploader)->userName."<br/>";

$this->beginWidget(
	'booster.widgets.TbModal',
	array(
		'id' => 'imageModal'.$s->screenshotid,
		'htmlOptions' => array(
			'width'=> '100%',
		)
		)
	); 
?> 
<div>
	<a class="close" data-dismiss="modal">&times;</a>
	<?php
		echo CHtml::image(
			$this->createAbsoluteUrl('screenShot/display', array('id'=>$s->screenshotid)), 
			'Screenshot of '.$model->bugTitle,
			array(
				'title'=>'image title here',
				'width'=>'100%',
			) 
		);
	?>
</div>
 
<?php $this->endWidget();
}
?>